### ISSUE TITLE
Automatic Mesos Cluster Testing

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#754] opened 2015-10-22 19:13 UTC
As a developer, I can deploy a mesos cluster and verify that the components are running and available on a scheduled basis

Acceptance Criteria:
A button is available on the page to observe if the build is passing
Components Zookeeper is up
Mesos is up
Marathon is up
Consul is up
A 'hello world' application can be triggered on Marathon

Additional Info:
Jenkins or another similar tool can be utilized for this purpose

**Comment by eirslett** [comment] 2015-10-23 08:41
We do this on our CI - we deploy the cluster (mi-deploy), then run curl against the consul API in a loop, until it tells us all the nodes are healthy. (Meaning that distributive has run all the health checks and they succeeded)

**Comment by frankscholten** [comment] 2015-10-23 09:12
Checkout minimesos.org

**Comment by siddharthist** [comment] 2015-11-23 23:10
Duplicate of #163, #547

**Closed by siddharthist** 2015-11-23 23:10 UTC
