### ISSUE TITLE
Forward all Docker container logs to local Rsyslog agent

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#156] opened 2015-04-08 10:51 UTC
Consider using:
* Docker 1.6 native support (ideal)
  * Get latest docker builds at http://cbs.centos.org
  * http://cbs.centos.org/koji/buildinfo?buildID=919
* Logspout (less ideal)

**Comment by tymofii-polekhin** [comment] 2015-04-10 12:45
https://github.com/CiscoCloud/microservices-infrastructure/issues/156

State: failed

**Comment by tymofii-polekhin** [comment] 2015-04-17 09:35
Just checked out new Docker 1.6 with --log-driver syslog
Was able to route a container logs to host syslog, and then rsyslog sends it to container with logstash

**Comment by keithchambers** [comment] 2015-04-19 15:36
@tymofii-polekhin Awesome! 

Now that we know we have logstash working for 0.3 I recommend forwarding all Docker container logs directly to logstash (and bypassing rsyslog).

**Comment by loshkovskyi** [comment] 2015-04-24 15:44
Some updates on this issue:

1. Docker 1.6 has not been packaged for CentOS 7 yet. We could use the [virt7-testing](http://wiki.centos.org/Cloud/Docker) repo, but I'm not sure if we want to do that.
2. There are two logging systems in CentOS 7: journald and rsyslog. The last one will get deprecated one day and we'll need to track that. Journald is not currently supported by Logstash.
3. Some our services are not run in containers. I'm going to investigate how we could alter our playbooks and forward logs of such services to Logstash.

**Comment by maier** [comment] 2015-04-24 20:43
Is there any reason to not have logstash read the container logs directly? (the older jsonfile type)

Configuration input snippet:

```
input {
    file {
        path => "/docker_logs/*/*-json.log"
    }
}
```

Mounting the log location to be followed:

```
docker run ... -v /var/lib/docker/containers:/docker_logs:ro ...
```

Is using [r]syslog more efficient? And as @loshkovskyi mentioned, syslog will be phased out in favor of journald the move to systemd. Though, that will probably take quite some time.

**Comment by loshkovskyi** [comment] 2015-04-25 16:36
Thank you @maier. It's a good idea to read the logs directly and it's easy to implement. But I thought it's less secure than using [r]syslog.

Anyway, I'm hitting the following bug: https://github.com/elastic/logstash/issues/3033 (it might be related to JRuby). So, the file input is currently broken in the latest Logstash 1.5 RC3.

**Comment by loshkovskyi** [comment] 2015-04-27 20:14
I think I have found where the problem is. Logstash is written in JRuby which requires `libc` to be present in the system. Whereas Alpine Linux provides Java compiled with `musl`:
```
bash-4.3# head -n 1 /etc/issue 
Welcome to Alpine Linux 3.1
bash-4.3# ldd /usr/lib/jvm/java-1.7-openjdk/bin/java|grep libc
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fb4b68a3000)
```
For example, Ubuntu provides Java with the `libc` support:
```
root@3633e1c32c48:~# head -n 1 /etc/issue
Ubuntu 14.04.2 LTS \n \l
root@3633e1c32c48:~# ldd /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java|grep libc
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa2e5fa5000)
```
That is the reason we are having such errors from JRuby and Logstash keeps failing to start when using the input file plugin.

I don't see any solution but switching from Alpine Linux to another lightweight image.
What is your opinion on that?

For example, I have just tested https://github.com/jeanblanchard/docker-busybox-java:
```
bash-4.3# ldd /opt/jdk/bin/java|grep libc
	libc.so.6 => /lib/libc.so.6 (0x00007f0176f20000)
```
I'm able to start Logstash and use its basic plugins with no errors from JRuby any more.

**Comment by stevendborrelli** [comment] 2015-04-27 20:24
I'm ok with using another base. Can we open an issue with Alpine Linux and see what their answer is?

**Comment by loshkovskyi** [comment] 2015-04-28 10:05
I have submitted the following issues:
https://bugs.alpinelinux.org/issues/4127
https://bugs.alpinelinux.org/issues/4128

**Comment by brism** [comment] 2015-04-30 03:42
The Project Atomic folks have added `journald` as a log driver in Docker 1.7. I know that's a ways off but something to think about.

http://www.projectatomic.io/blog/2015/04/logging-docker-container-output-to-journald/

**Comment by loshkovskyi** [comment] 2015-04-30 07:45
Thank you, Brian! I'll keep an eye on it.

**Comment by stevendborrelli** [comment] 2015-06-01 02:39
Docker 1.6 has been included with Centos7 for a couple of weeks and includes a syslog driver. Should we just enable that?

**Comment by loshkovskyi** [comment] 2015-06-03 10:04
@stevendborrelli sorry for a long reply. I've already tested the new syslog driver in CentOS 7 and I have several concerns with it. The Logstash output is disabled by default, that is we don't send logs anywhere. If we enable the syslog driver, the Docker containers json logs won't be created anymore. Having such logs is useful for debugging. Furthermore, the `/var/log/messages` file starts growing extremely fast with the syslog option enabled, as all of the containers' logs are written there.

**Comment by stevendborrelli** [comment] 2015-06-03 14:39
@loshkovskyi great answer. I'm going to close this issue and we can go with the Logstash solution that allows the user to forward to an external service.

**Closed by stevendborrelli** 2015-06-03 14:39 UTC
Labels: enhancement
