### ISSUE TITLE
Wrong attached storage device name in OpenStack

### ISSUE THREAD

**Issue by rida4** [CiscoCloud/microservices-infrastructure#399] opened 2015-05-29 17:16 UTC
When we attach a volume as "/dev/vdb" (for example) it may appear on the guest machine with any other name (for example, "/dev/vdc"). That "slighlty" breaks our playbooks.
 bug description https://bugs.launchpad.net/nova/+bug/1217874

**Comment by cdmitri** [comment] 2015-05-29 18:52
@rida4 Could you please provide more info on what we're trying to do in which playbook? Usually so far it's been just adding everything as /dev/vdb if we run in from CLI

**Comment by OleksandrBerchenko** [comment] 2015-06-01 10:44
If you are adding an external volume like "/dev/vdb" (either via nova or Horizon), there is a high chance that it will be added exactly like "/dev/vdb".  But there is still a small chance that it will be added like "/dev/vdc" or something else.  In other words, nobody can guarantee you an exact path on the guest machine.  There is a bug for OpenStack already: https://bugs.launchpad.net/nova/+bug/1217874 .  It's a very old issue and I'm not sure it will be ever fixed.

**Comment by cdmitri** [comment] 2015-06-01 15:26
Let's do a workaround and main thing - test it with TF - if it gets fixed
in latest openstack, it still might get a while for that fix to get to our
infra.

On Mon, Jun 1, 2015 at 3:44 AM, OleksandrBerchenko <notifications@github.com

**Comment by loshkovskyi** [comment] 2015-06-09 18:31
You can use the following command to set the required device name ([docs](http://docs.openstack.org/openstack-ops/content/attach_block_storage.html)):
```
nova volume-attach <server> <volume> [<device>]
```

with Terraform it's possible to go this way:
```
provider "openstack" {
    user_name  = "admin"
    tenant_name = "admin"
    password  = "pwd"
    auth_url  = "http://myauthurl:5000/v2.0"
}

resource "openstack_blockstorage_volume_v1" "volume_1" {
  region = "my_region"
  name = "tf-test-volume"
  description = "first test volume"
  size = 1
}

resource "openstack_compute_instance_v2" "test-server" {
  name = "tf-test"
  image_id = "image_id"
  flavor_id = "flavor_id"
  key_pair = "my_key_pair_name"
  security_groups = ["test-group-1"]
  volume {
    volume_id = "${ openstack_blockstorage_volume_v1.volume_1.id }"
    device = "/dev/vdd"
  }
}
```
Run usual `terraform plan` and `terraform apply` and check the instance attachments:
```
cinder show tf-test-volume|grep device
```
It should be `/dev/vdd` as to this example.

**Comment by noahjl** [comment] 2015-06-10 19:53
This is likely caused by UUID, or path changing due to how the hypervisor handles the drives. RHEL7 variants really should not suffer from this anymore... 

If we could verify cause on a server this occurs on we could guarantee a persistent naming method using udev rules. 

In the interim we could just slap a label on the disks, or force the naming to be by path.

If we do this via TF i think the remote_exec provisioner may be ideal for it.. something like; 
`
resource "openstack_compute_instance_v2" "test-server" {
  name = "tf-test"
  image_id = "image_id"
  flavor_id = "flavor_id"
  key_pair = "my_key_pair_name"
  security_groups = ["test-group-1"]
  volume {
    volume_id = "${ openstack_blockstorage_volume_v1.volume_1.id }"
    device = "/dev/vdd"
  }
  provisioner "remote-exec" {
        inline = [
         "(lsblk -I 8 -o NAME,UUID -> array; for x in array[@]; do echo 
             KERNEL==”sd?1″, SUBSYSTEM==”block”, PROGRAM==”/bin/lsblk -o UUID /dev/$parent | grep -v -e UUID -e '^$'”, RESULT==”$(array[UUID]) ″, SYMLINK+=”vdd%n" >> /etc/udev/rules.d/25-persistent-vdisknames-conf)" 
        ]
  }
}

The above is far from correct or even close - but just wanted to get a pseudo though out there. 

References: 
https://dbakerber.wordpress.com/2014/08/08/udev-rules/ (the above theory more or less)
https://wiki.archlinux.org/index.php/Persistent_block_device_naming
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/persistent_naming.html

**Comment by OleksandrBerchenko** [comment] 2015-06-24 06:59
Workarounded in qa/features-master-integration branch (https://github.com/CiscoCloud/microservices-infrastructure/pull/513).

Closing.

**Closed by OleksandrBerchenko** 2015-06-24 06:59 UTC
