### ISSUE TITLE
Kubernetes deployment testing

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#752] opened 2015-10-22 18:41 UTC

**Comment by PeterLamar** [comment] 2015-10-22 18:44
As a developer, I can run the tests that validate the deployment of Kubernetes is valid

Acceptance Criteria:

Every Ansible task should be tested

Additional Info:
https://github.com/CiscoCloud/distributive

**Comment by siddharthist** [comment] 2015-11-23 22:59
Duplicate of #753. We now have a tech preview of Kubernetes available, and are working on further integration.

**Closed by siddharthist** 2015-11-23 22:59 UTC
