### ISSUE TITLE
Fails to do ssh with mi-deploy while deploying to AWS

### ISSUE THREAD

**Issue by saswatp** [CiscoCloud/microservices-infrastructure#709] opened 2015-09-22 19:22 UTC
Using mi-deploy CLI for AWS , I am running into an issue where it’s not able to SSH into the host to do software configuration through Ansible. However, If I manually run ansible-playbook command for MI deployment from the same box it works fine.
```

GATHERING FACTS *************************************************************** 
<54.152.204.132> ESTABLISH CONNECTION FOR USER: centos
<54.152.204.132> REMOTE_MODULE setup
<54.152.204.132> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cloud-user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 54.152.204.132 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.61-103087589510290 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.61-103087589510290 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.61-103087589510290'
fatal: [pb-saspraha-control-01] => SSH Error: ssh: connect to host 54.152.204.132 port 22: Connection timed out
    while connecting to 54.152.204.132:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
<107.21.50.194> ESTABLISH CONNECTION FOR USER: centos
<107.21.50.194> REMOTE_MODULE setup
<107.21.50.194> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cloud-user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 107.21.50.194 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.61-169534109504757 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.61-169534109504757 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.61-169534109504757'
fatal: [pb-saspraha-control-02] => SSH Error: ssh: connect to host 107.21.50.194 port 22: Connection timed out
    while connecting to 107.21.50.194:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
<107.21.44.108> ESTABLISH CONNECTION FOR USER: centos
<107.21.44.108> REMOTE_MODULE setup
<107.21.44.108> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cloud-user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 107.21.44.108 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998'
fatal: [pb-saspraha-control-03] => SSH Error: ssh: connect to host 107.21.44.108 port 22: Connection timed out
    while connecting to 107.21.44.108:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
<107.21.47.13> ESTABLISH CONNECTION FOR USER: centos
<107.21.47.13> REMOTE_MODULE setup
<107.21.47.13> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cloud-user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 107.21.47.13 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.62-96761301654828 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.62-96761301654828 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.62-96761301654828'
fatal: [pb-saspraha-worker-001] => SSH Error: ssh: connect to host 107.21.47.13 port 22: Connection timed out
    while connecting to 107.21.47.13:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
```

Any clue on what’s going wrong with mi-deploy in this case ?

**Comment by saswatp** [comment] 2015-09-22 19:31
Here is the SSH command that is used : 

ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cloud-user/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 107.21.44.108 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998'

--------

On further debugging , it seems the following command fails to execute during ssh login : 

debug1: Sending command: /bin/sh -c mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998 && echo $HOME/.ansible/tmp/ansible-tmp-1442949717.62-276064063635998

debug2: channel 2: request exec confirm 1
debug3: mux_session_confirm: sending success reply
debug2: callback done
debug2: channel 2: open confirm rwindow 0 rmax 32768
debug1: mux_client_request_session: master session id: 2
debug2: channel_input_status_confirm: type 99 id 2
debug2: PTY allocation request accepted on channel 2
debug2: channel 2: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 2
debug2: exec request accepted on channel 2
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug3: mux_exit_message: channel 2: exit message, exitval 1
debug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0
debug2: channel 2: rcvd eow
debug2: channel 2: close_read
debug2: channel 2: input open -> closed
debug2: channel 2: rcvd eof
debug2: channel 2: output open -> drain
debug2: channel 2: rcvd close
debug3: channel 2: will not send data after close

mkdir: missing operand

**Comment by siddharthist** [comment] 2015-09-22 19:41
@saswatp Have you tried retrying the process? That usually works for me. I think what might be the issue is that `mi-deploy` tries to run ansible immediately after terraforming, which might not give the machines time to become ready.

**Comment by ryane** [comment] 2015-09-22 19:46
I wonder if we could run `playbooks/wait-for-hosts.yml` (or something equivalent) in between Terraform and ansible provisioning.

**Comment by siddharthist** [comment] 2015-09-22 19:48
That would be very easy to do, I can try patching that.

**Comment by saswatp** [comment] 2015-09-22 21:17
Yes , I just tried retry option and thought it got stuck as didn't show any output for long long time. Later I realized that It was actually deploying ... @ryane  - That's a good idea. 
@siddharthist - Another thing I observed is that if i run in debug mode --verbosity "debug" , on the ssh failure , it simply exits without prompting me to retry.

**Comment by siddharthist** [comment] 2015-09-23 00:00
@saswatp Let's close this and open two new unrelated issues:
 1. `mi-deploy` doesn't allow for retrying when `verbosity=debug`
 2. `mi-deploy` should use `wait-for-hosts.yml` before running Ansible

**Closed by siddharthist** 2015-09-23 00:00 UTC
