### ISSUE TITLE
CentOS - Playbook Installation failed for vault

### ISSUE THREAD

**Issue by deepagargit** [CiscoCloud/microservices-infrastructure#712] opened 2015-09-23 07:22 UTC
I am getting error when executing MI playbooks with Vagrant.

Please suggest any workaround or fix?

=======================================================================

OS : CentOS
MI : wget https://github.com/CiscoCloud/microservices-infrastructure/archive/0.3.2.tar.gz
Vagrant : 1.7.4
VirtualBox : 4.3

======================================================================
```
==> default: TASK: [common | clean hosts file] *********************************************
==> default: skipping: [default] => (item=^127.0.0.1 default.*)
==> default: skipping: [default] => (item=^::1 default.*)
==> default:
==> default: TASK: [collectd | install collectd packages] **********************************
==> default: ok: [default] => (item=collectd,libsemanage-python)
==> default:
==> default: TASK: [collectd | create collectd plugin directory] ***************************
==> default: changed: [default]
==> default:
==> default: TASK: [collectd | configure collectd] *****************************************
==> default: changed: [default]
==> default:
==> default: TASK: [collectd | authorize collectd to make tcp connections] *****************
==> default: skipping: [default]
==> default:
==> default: TASK: [collectd | check if collectd is authorized to connect to docker] *******
==> default: skipping: [default]
==> default:
==> default: TASK: [collectd | copy collectd selinux docker policy] ************************
==> default: skipping: [default]
==> default:
==> default: TASK: [collectd | authorize collectd to connect to docker] ********************
==> default: skipping: [default]
==> default:
==> default: TASK: [collectd | enable collectd] ********************************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | set logrotate interval to daily] ***************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | set logrotate retention period to 7 days] ******************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | configure mesos logrotate] *********************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | create mesos archive] **************************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | configure docker logrotate] ********************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | configure zookeeper logrotate] *****************************
==> default: changed: [default]
==> default:
==> default: TASK: [logrotate | create zookeeper archive] **********************************
==> default: changed: [default]
==> default:
==> default: TASK: [consul-template | install consul-template] *****************************
==> default: ok: [default]
==> default:
==> default: TASK: [consul-template | configure consul-template] ***************************
==> default: changed: [default]
==> default:
==> default: TASK: [consul-template | enable consul-template] ******************************
==> default: changed: [default]
==> default:
==> default: TASK: [docker | install latest device-mapper-libs] ****************************
==> default: ok: [default]
==> default:
==> default: TASK: [docker | install docker] ***********************************************
==> default: failed: [default] => {"changed": true, "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirror.hmc.edu\n * epel: mirror.umd.edu\n * extras: mirror.es.its.nyu.edu\n * updates: mirror.hmc.edu\nResolving Dependencies\n--> Running transaction check\n---> Package docker.x86_64 0:1.7.1-115.el7 will be installed\n--> Processing Dependency: docker-selinux >= 1.7.1-115.el7 for package: docker-1.7.1-115.el7.x86_64\n--> Running transaction check\n---> Package docker-selinux.x86_64 0:1.6.2-14.el7.centos will be updated\n---> Package docker-selinux.x86_64 0:1.7.1-115.el7 will be an update\n--> Processing Conflict: docker-engine-1.7.0-1.el7.centos.x86_64 conflicts docker\n--> Restarting Dependency Resolution with new changes.\n--> Running transaction check\n---> Package docker-engine.x86_64 0:1.7.0-1.el7.centos will be updated\n---> Package docker-engine.x86_64 0:1.8.2-1.el7.centos will be an update\n--> Processing Conflict: docker-engine-1.8.2-1.el7.centos.x86_64 conflicts docker-io\n--> Processing Conflict: docker-engine-1.8.2-1.el7.centos.x86_64 conflicts docker\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
==> default: msg: Error: docker-engine conflicts with docker-1.7.1-115.el7.x86_64
==> default:
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default: common | install pip --------------------------------------------------- 15.29s
==> default: common | install system utilities -------------------------------------- 10.09s
==> default: common | install distributive ------------------------------------------- 9.44s
==> default: common | update setuptools and pip -------------------------------------- 8.89s
==> default: docker | install docker ------------------------------------------------- 8.57s
==> default: consul-template | install consul-template ------------------------------- 7.82s
==> default: docker | install latest device-mapper-libs ------------------------------ 5.10s
==> default: common | enable EPEL repo ----------------------------------------------- 2.33s
==> default: collectd | install collectd packages ------------------------------------ 0.99s
==> default: collectd | enable collectd ---------------------------------------------- 0.47s
==> default:            to retry, use: --limit @/root/vagrant.retry
==> default:
==> default: default                    : ok=29   changed=20   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

========================================================================

=======================================================================

OS : CentOS
MI : latest git clone https://github.com/CiscoCloud/microservices-infrastructure.git
Vagrant : 1.7.4
VirtualBox : 4.3

======================================================================
```
==> default: TASK: [logstash | forward all logs from rsyslog to logstash] ******************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [handlers | reload consul] ******************************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [handlers | wait for consul to listen] ******************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [docker | restart rsyslog] ******************************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [consul | restart nginx-consul] *************************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [logstash | reload systemd daemon] **********************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [logstash | enable and start logstash] ******************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [logstash | restart logstash] ***************************************
==> default: changed: [default]
==> default:
==> default: TASK: [vault | install vault] *************************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | configure vault service] ***************************************
==> default: changed: [default]
==> default:
==> default: TASK: [vault | create vault directories] **************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | configure vault] ***********************************************
==> default: changed: [default]
==> default:
==> default: TASK: [vault | enable vault] **************************************************
==> default: changed: [default]
==> default:
==> default: TASK: [vault | wait for vault port] *******************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | initialize vault] **********************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | extract keys] **************************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | extract root token] ********************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | create unseal script] ******************************************
==> default: ok: [default]
==> default:
==> default: TASK: [vault | update security.yml with token] ********************************
==> default: changed: [default]
==> default:
==> default: NOTIFIED: [vault | restart vault] *********************************************
==> default: failed: [default] => {"changed": true, "cmd": ["systemctl", "restart", "vault"], "delta": "0:00:02.180131", "end": "2015-09-23 06:01:17.312769", "rc": 1, "start": "2015-09-23 06:01:15.132638", "warnings": []}
==> default: stderr: Job for vault.service failed. See 'systemctl status vault.service' and 'journalctl -xn' for details.
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: TASK: [vault | create consul configuration directory] *************************
==> default: FATAL: no hosts matched or all hosts have already failed -- aborting
==> default:
==> default:
==> default: PLAY RECAP ********************************************************************
==> default: logstash | restart logstash -------------------------------------------- 29.27s
==> default: dnsmasq | install packages --------------------------------------------- 19.25s
==> default: common | install pip --------------------------------------------------- 15.02s
==> default: common | install system utilities -------------------------------------- 11.48s
==> default: common | install distributive ------------------------------------------ 10.01s
==> default: consul | restart nginx-consul ------------------------------------------- 9.56s
==> default: vault | install vault --------------------------------------------------- 9.19s
==> default: consul-template | install consul-template ------------------------------- 8.38s
==> default: consul | install consul ------------------------------------------------- 8.38s
==> default: docker | install collectd docker plugin dependencies -------------------- 8.25s
==> default:            to retry, use: --limit @/root/vagrant.retry
==> default:
==> default: default                    : ok=126  changed=93   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

======================================================================

**Comment by deepagargit** [comment] 2015-09-23 17:22
The issue is also seen on MAC with 0.3.2.tar.gz

OS : MAC
MI : wget https://github.com/CiscoCloud/microservices-infrastructure/archive/0.3.2.tar.gz
Vagrant : 1.7.4
VirtualBox : 4.3

**Comment by deepagargit** [comment] 2015-09-23 17:23
The latest MI works good with MAC, but fails on CentOS vault installation.

Any inputs what could be broken?

OS : MAC
MI : latest git clone https://github.com/CiscoCloud/microservices-infrastructure.git
Vagrant : 1.7.4
VirtualBox : 4.3

**Comment by deepagargit** [comment] 2015-09-24 08:06
The vault evaluation on spawned VM after above error.

It looks vault is installed good.

What else could be investigated and how this issue could get fixed?

===========================================================================


[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'systemctl status vault.service'
vault.service - vault
   Loaded: loaded (/usr/lib/systemd/system/vault.service; enabled)
   Active: active (running) since Thu 2015-09-24 07:55:49 UTC; 5min ago
  Process: 6092 ExecStartPost=/bin/bash -c [ -f /etc/vault/vault.unseal ] && /etc/vault/vault.unseal (code=exited, status=0/SUCCESS)
 Main PID: 6091 (vault)
   CGroup: /system.slice/vault.service
           └─6091 /usr/bin/vault server -config=/etc/vault/vault.config

Connection to 127.0.0.1 closed.

===========================================================================


[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'journalctl -xn'
No journal files were found.
Connection to 127.0.0.1 closed.

===========================================================================


[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'vault --version'
bash: /usr/bin/vault: Permission denied
Connection to 127.0.0.1 closed.

===========================================================================


[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'sudo vault --version'
Vault v0.1.0-dev (39f014e0b6eeb128c1626db85e248fa34f4acbf6+CHANGES)
Connection to 127.0.0.1 closed.

===========================================================================


[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'curl http://localhost:8500/v1/catalog/services'
{"consul":[],"docker":[]}Connection to 127.0.0.1 closed.

===========================================================================

[@CentOS7 microservices-infrastructure]$ vagrant ssh -c 'sudo vault --help'
usage: vault [-version] [-help] <command> [args]

Common commands:
    delete           Delete operation on secrets in Vault
    help             Look up the help for a path
    read             Read data or secrets from Vault
    renew            Renew the lease of a secret
    revoke           Revoke a secret.
    server           Start a Vault server
    status           Outputs status of whether Vault is sealed and if HA mode is enabled
    write            Write secrets or configuration into Vault

All other commands:
    audit-disable    Disable an audit backend
    audit-enable     Enable an audit backend
    audit-list       Lists enabled audit backends in Vault
    auth             Prints information about how to authenticate with Vault
    auth-disable     Disable an auth provider
    auth-enable      Enable a new auth provider
    init             Initialize a new Vault server
    mount            Mount a logical backend
    mounts           Lists mounted backends in Vault
    policies         List the policies on the server
    policy-delete    Delete a policy from the server
    policy-write     Write a policy to the server
    remount          Remount a secret backend to a new path
    seal             Seals the vault server
    token-create     Create a new auth token
    token-renew      Renew an auth token
    token-revoke     Revoke one or more auth tokens
    unmount          Unmount a secret backend
    unseal           Unseals the vault server
    version          Prints the Vault version

Connection to 127.0.0.1 closed.

**Comment by deepagargit** [comment] 2015-09-24 08:14
The MI fails in playbook systemctl restart vault while 'vagrant up'.

But manually restarting vault in VM is success.

==========================================================

[@CentOS7 microservices-infrastructure]$ vagrant ssh

===============================================================

[vagrant@default ~]$ sudo systemctl status vault
vault.service - vault
   Loaded: loaded (/usr/lib/systemd/system/vault.service; enabled)
   Active: active (running) since Thu 2015-09-24 07:55:49 UTC; 15min ago
  Process: 6092 ExecStartPost=/bin/bash -c [ -f /etc/vault/vault.unseal ] && /etc/vault/vault.unseal (code=exited, status=0/SUCCESS)
 Main PID: 6091 (vault)
   CGroup: /system.slice/vault.service
           └─6091 /usr/bin/vault server -config=/etc/vault/vault.config

Sep 24 07:55:49 default bash[6092]: Unseal Progress: 0
Sep 24 07:55:49 default bash[6092]: Sealed: false
Sep 24 07:55:49 default bash[6092]: Key Shares: 5
Sep 24 07:55:49 default bash[6092]: Key Threshold: 3
Sep 24 07:55:49 default bash[6092]: Unseal Progress: 0
Sep 24 07:55:49 default systemd[1]: Started vault.
Sep 24 07:56:12 default vault[6091]: 2015/09/24 07:56:12 [INFO] core: acquired lock, enabling active operation
Sep 24 07:56:12 default vault[6091]: 2015/09/24 07:56:12 [INFO] core: post-unseal setup starting
Sep 24 07:56:12 default vault[6091]: 2015/09/24 07:56:12 [INFO] rollback: starting rollback manager
Sep 24 07:56:12 default vault[6091]: 2015/09/24 07:56:12 [INFO] core: post-unseal setup complete

=========================================================

[vagrant@default ~]$
[vagrant@default ~]$
[vagrant@default ~]$ sudo systemctl restart vault
[vagrant@default ~]$
[vagrant@default ~]$

==========================================================

[vagrant@default ~]$ sudo systemctl status vault
vault.service - vault
   Loaded: loaded (/usr/lib/systemd/system/vault.service; enabled)
   Active: active (running) since Thu 2015-09-24 08:12:06 UTC; 4s ago
  Process: 6867 ExecStartPost=/bin/bash -c [ -f /etc/vault/vault.unseal ] && /etc/vault/vault.unseal (code=exited, status=0/SUCCESS)
 Main PID: 6866 (vault)
   CGroup: /system.slice/vault.service
           └─6866 /usr/bin/vault server -config=/etc/vault/vault.config

Sep 24 08:12:06 default bash[6867]: Key Threshold: 3
Sep 24 08:12:06 default bash[6867]: Unseal Progress: 0
Sep 24 08:12:06 default bash[6867]: Sealed: false
Sep 24 08:12:06 default bash[6867]: Key Shares: 5
Sep 24 08:12:06 default bash[6867]: Key Threshold: 3
Sep 24 08:12:06 default bash[6867]: Unseal Progress: 0
Sep 24 08:12:06 default bash[6867]: Sealed: false
Sep 24 08:12:06 default bash[6867]: Key Shares: 5
Sep 24 08:12:06 default bash[6867]: Key Threshold: 3
Sep 24 08:12:06 default bash[6867]: Unseal Progress: 0
Sep 24 08:12:06 default systemd[1]: Started vault.
[vagrant@default ~]$

================================================================

[vagrant@default ~]$ ps -ef | grep vault
root      6866     1  0 08:12 ?        00:00:00 /usr/bin/vault server -config=/etc/vault/vault.config
vagrant   7002  6817  0 08:14 pts/0    00:00:00 grep --color=auto vault

**Comment by deepagargit** [comment] 2015-09-29 08:28
Could someone share the MANTL support contacts?

There has been no response for bug reported for MANTL on CentOS.

**Comment by ryane** [comment] 2015-09-29 14:20
Can you confirm that you have the following when you run `vagrant box list`?

    CiscoCloud/microservices-infrastructure (virtualbox, 0.5)

If you have any other older versions of the CiscoCloud/microservices-infrastructure box, try removing them. 

I haven't seen that vault failure. If you run `vagrant provision` after it fails, does the build complete successfully or does it still fail? Also, if you see the failure again, run `journalctl` with `sudo` to see the logs. Perhaps they will provide a clue as to what the problem is.

**Comment by siddharthist** [comment] 2015-11-23 21:43
@deepagargit Are you still seeing this issue?

**Comment by stevendborrelli** [comment] 2015-12-30 02:46
Going to close this, as we are refactoring the vault task.

**Closed by stevendborrelli** 2015-12-30 02:46 UTC
Labels: community input, vagrant
