### ISSUE TITLE
Support Windows microservices deployment

### ISSUE THREAD

**Issue by tooda02** [CiscoCloud/microservices-infrastructure#179] opened 2015-04-16 17:36 UTC
microservices-infrastructure currently will not deploy in Windows.  Most of the issues are with Ansible, which [explicitly does not support Windows as a controller and has no plans of doing so] (http://docs.ansible.com/intro_windows.html#reminder-you-must-have-a-linux-control-machine).

Issues below are classified by deployment method (native, Cygwin, or Ansible in VirtualBox).  One issue affecting all deployment approaches is that the Vagrantfile is forwarding 1000 ports (31000-32000).   Each one of these adds a fairly verbose string to the VBoxmanage command (e.g. "--natpf1", "tcp31000,tcp,,31000,,31000"), and the resultant command ends up longer that the Windows max of 32768.  The workaround is to reduce the number of ports forwarded to 750 or fewer, with 700 recommended.

## Issues with Setup on Native Windows
* It is necessary to [install PyCrypto manually] (http://www.voidspace.org.uk/python/modules.shtml#pycrypto) prior to installing other requirements.
* It is necessary to have openssh in the path, which is not standard on Windows.  One way of doing this is to install git and add C:\Program Files (x86)\Git\bin to the path.  
* A C compiler is needed to run pip -f requirements.txt (the symptom of a missing compiler is the cryptic error message "vcvarsall.bat not found").  Microsoft has a [Microsoft Visual C++ Compiler for Python 2.7] (http://www.microsoft.com/en-us/download/details.aspx?id=44266).  It is also possible to use [Visual Studio C++ 2008 Express Edition] (http://download.microsoft.com/download/A/5/4/A54BADB6-9C3F-478D-8657-93B3FC9FE62D/vcsetup.exe), but this is no longer supported by Microsoft and can't be registered.  Per the StackOverflow page [Unable to find vcvarsall.bat] (http://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat), a workaround is delete or rename HKCU\Software\Microsoft\VCExpress\9.0\SourceControl\Registration.
* The security-update command must be issued as "python security-update"

### Requirements
* Install and/or update Cygwin to include the packages gcc g++, openssh, python, python-crypto, python-paramiko, python-setuptools, and wget
* You must use Cygwin's Python.  If Python is installed on native Windows, make sure it is not in the Cygwin path.  One way of doing this is add the line:

> PATH=`echo $PATH | sed -e 's/:[^:]*python[^:]*//ig'

to your .bashrc file.
* Ansible startup will fail with the error "ansible-playbook not in PATH".  To work around this, it's necessary to add an ansible-playbook.bat file to the path.  This should take the form:

>@echo off
>setlocal
>set CYGWIN=C:/Cygwin
>set SH=%CYGWIN%/bin/bash.exe
>echo %* | sed -e "s/\(inventory-file=\)[^\.]*/\1/" | sed -e "s/\(--private-key=\)[^ ]*\(\/[^ ]*\) /\1\/cygdrive\/c\/home\/%USERNAME%\2 /"
>"%SH%" -c "/bin/ansible-playbook `echo %* | sed -e 's/\(inventory-file=\)[^\.]*/\1/' | sed -e 's/\(--private-key=\)[^ ]*\(\/[^ ]*\) /\1\/cygdrive\/c\/home\/%USERNAME%\2 /'`"

The first sed command above changes the absolute path to the inventory file to a relative path.  The second changes the path to the private_key file from the default to a copy in the home directory.  This is required because Vagrant creates the file with open permissions, and these cannot be changed in a shared directory.  See the issues section for more on this.
* See [Running Vagrant with Ansible Provisioning on Windows] (http://www.azavea.com/blogs/labs/2014/10/running-vagrant-with-ansible-provisioning-on-windows/) for an overview.

### Issues
The major issue with this approach is the private_key that security-setup creates in the virtualbox directory.  Vagrant sets open permissions to this (766) and does not allow them to be changed (it ignores chmod to a file in a shared directory).  Permissions can be changed to the required 600 manually, but the effective permissions depend on how the file is accessed.  On Windows, a path beginning /cygdrive/c shows the correct restricted permissions; a path beginning C:/ shows open permissions.  Unfortunately, only the latter path is available to the Ansible provisioner.

As noted above, one possible workaround to this issue is to copy the private_key file to a non-shared directory.  Unfortunately, the Ansible provisioner appears to have no access to most of the Windows system (for example, home directories are inaccessible).  This ultimately was a showstopper for this approach.

## Deploy Ansible in the Vagrant Machine
This approach is described in the GitHub project [JJG-Ansible-Windows] (https://github.com/geerlingguy/JJG-Ansible-Windows).  However:
* The provided script must be updated to install gcc and wget and to remove the code installing Ansible roles from requirements.txt
* The ansible-playbook command must be updated to set all required extra-vars
* There are a number of issues that with Ansible playbook deployment.  Among them:
 * script roles/console/files/consul-acl-bootstrap.sh contains embedded returns, causing a spurious "not found" error during consul deployment
 * "update security.yml" step in agent_act.yml fails with "Text file busy", which turns out to be a [known issue with the Windows version of VirtualBox] (https://gist.github.com/koseki/d3f9e5fa23c69dd52b17)

**Comment by keithchambers** [comment] 2015-04-16 20:15
@tooda02 thank your for opening this issue!

We'll need to take a step back and consider how we can make this simple and reliable across Windows and OSX.  Please give us a little time.

**Comment by BrianHicks** [comment] 2015-06-18 11:10
@tooda02 can you try latest master? As of 0.3.0 Vagrant runs are contained within the Vagrant box.

**Comment by tooda02** [comment] 2015-06-18 14:24
@BrianHicks Got similar errors in security-setup in both native Windows and Cygwin.  

Native Windows (same results running as standard user or Administrator):

> C:\cisco\go\src\github.com\CiscoCloud\microservices-infrastructure>pip install -r requirements.txt .\security-setup vagrant up
 Exception:
 Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
   status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "C:\Python27\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "C:\Python27\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "C:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', '.\\security-setup', 'at', '\\security-setup')

> Storing debug log for failure in C:\Users\Admin\pip\pip.log

And Cygwin running as Administrator:

> Admin@tooda02 /cygdrive/c/cisco/go/src/github.com/CiscoCloud/microservices-infrastructure
$ pip install -r requirements.txt ./security-setup vagrant up
You are using pip version 6.1.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/commands/install.py", line 308, in run
    name, None, isolated=options.isolated_mode,
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 220, in from_line
    isolated=isolated)
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/req/req_install.py", line 79, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', './security-setup', 'at', '/security-setup')

Cygwin requirements setup fails immediately with a segmentation fault if run as a standard user.

**Comment by BrianHicks** [comment] 2015-06-18 14:28
it looks like you're running three commands at once. The commands should be, separately and in order:

1. `pip install -r requirements.txt`
2. `./security-setup`
3. `vagrant up`

However, if you're just wanting to run Vagrant, `vagrant up` should be all you need, the security setup and requirements installation is contained within the VM now.

**Comment by tooda02** [comment] 2015-06-18 19:10
Doh... was indeed trying to run three commands at once.

Unfortunately, vagrant up gets errors even when run alone.  It first failed because it needed rsync, which is not part of a default Cygwin installation (which also implies that it requires that Cygwin be installed and on the path).  But even after installing rsync into Cygwin, it fails with error:

> C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:109:in `rescue in execute': The filename or extension is too long. (206) (Vagrant::Util::Subprocess::LaunchError)

If you need it, I have the full log from running vagrant up.  My installation directory was "C:\cisco\go\src\github.com\CiscoCloud\microservices-infrastructure"

Once the filename issue is resolved, I'll retry with an OOB Cygwin and get a full list of the non-default commands required.

**Comment by BrianHicks** [comment] 2015-11-23 22:03
@tooda02 was this ever resolved for you? Did upgrading Vagrant and Virtualbox help?

**Comment by siddharthist** [comment] 2015-11-23 22:11
@BrianHicks I'll bring up my Windows Vagrant environment and post my results here, and we can see whether or not our current setup is compatible.

**Comment by eirslett** [comment] 2015-11-23 23:13
I develop on Windows. I tried running ansible on Windows, but I quickly found out it's much easier to provision a "meta" operations server in the cloud, with a linux os, and run ansible from that machine instead.

**Comment by siddharthist** [comment] 2015-11-23 23:36
@eirslett I think that since Ansible explicitly doesn't support windows as a controller, what we're discussing in this issue is if our Vagrant image can be run successfully on a Windows host. Unfortunately, we won't be able to provision machines from Windows until we move away from Ansible or they reverse their position and begin to support Windows.

**Comment by siddharthist** [comment] 2015-11-24 00:04
rsync didn't work, and a few other things needed fixing. Here's how to deploy successfully:

 1. Run `vagrant up`
 2. `vagrant ssh`
 3. `cd /vagrant`
 4. `yum install -y git ansible`
 5. `git clone https://github.com/CiscoCloud/microservices-infrastructure`
 6. `exit`
 7. `vagrant provision`

This all worked for me in Cygwin.

**Comment by eirslett** [comment] 2015-11-24 01:07
One issue with the Vagrant setup is that it's too simple - it's only one VM.
There should be at least 3:

- a "meta" provisioning VM, that basically only contains ansible and the mantl source code
- a bare centos VM, meant to be provisioned as a control node. (Or even 3 control VMs?)
- a bare centos VM, meant to be provisioned as a worker node.

[This is how it works](https://docs.vagrantup.com/v2/multi-machine/).

So, if the Mantl VM is provisioned from the Deploy VM, then it should work even on a Windows host. I suppose.

**Comment by siddharthist** [comment] 2015-11-24 01:54
@eirslett See #256

**Comment by siddharthist** [comment] 2015-11-24 07:26
Anyway, the next step is probably to document the above solution somewhere.

**Comment by siddharthist** [comment] 2015-11-27 08:12
Hopefully this will be fixed in #256, I'll test my solution on Windows as well.

**Comment by siddharthist** [comment] 2015-11-30 22:57
After more testing on Windows, it looks like the problem is only intermittent. I'm going to close this, please reopen if there are any more issues with Vagrant on Windows.

**Closed by siddharthist** 2015-11-30 22:57 UTC
Labels: enhancement, vagrant
