### ISSUE TITLE
docker-engine installation fails due to conflict with docker package

### ISSUE THREAD

**Issue by abn** [CiscoCloud/microservices-infrastructure#688] opened 2015-09-08 07:49 UTC
Raising this more so that this is logged and reasons for https://github.com/CiscoCloud/microservices-infrastructure/commit/c61031951d03c714527093f4e6f7ced691fd5e01 and https://github.com/CiscoCloud/microservices-infrastructure/commit/aba8d2fde4ba69215e2f57a36a9136bb3f9c176a are captured.

During deployment the "install docker packages" task fails with the following error.

```
TASK: [docker | install docker packages] ************************************** 
failed: [192.168.1.1] => (item=docker-engine-1.7.0,docker-selinux) => {"changed": true, "item": "docker-engine-1.7.0,docker-selinux", "rc": 1, "results": [<snipped>]}
msg: Error: docker-engine conflicts with docker-1.7.1-108.el7.centos.x86_64
```

The use case where the OS provided docker package is pre-installed in the environment seems quite common. In my case, this was done so as to configure VM templates with specific `docker-storage` configurations.

1. Should this be supported from the project's perspective?
2. If so, would skipping this task if docker is already installed be sufficient? Or is there a need for using the docker-engine package from docker itself? ie., are there specific features that are leveraged that are not present in the OS packages? (Note: the OS package is 1.7.1 on CentOS 7.1).
3. If there is no need to use the docker repos, can we remove these tasks?

Happy to submit a PR, figured this is something that would require input from the maintainers. @BrianHicks maybe?

**Comment by eirslett** [comment] 2015-09-08 12:15
I think docker (the daemon/main project) was renamed to docker-engine at some point, which is why they conflict...

The way I think (reproducible builds), using *thin/minimal* CentOS images is the best way, because then mantl can behave the same across providers. Yhere are already some workarounds for different CentOS images, but in general that's a pretty big technical debt to manage. For example, how should it be automatically tested? (So the answer is no?) But then again, if docker-workarounds aren't supported in Mantl, that requires users of Mantl to have access to a clean CentOS image without Docker preinstalled. So if somebody only has thick CentOS bundles, that will be hard. Which cloud provider and image are you using? (At our place we use CentOS 7.0, not 7.1)

**Comment by abn** [comment] 2015-09-09 07:18
The package name 'docker-engine' seems to be only used by the docker upstream RPM repositories. Cannot find a reference for that in CentOS.

The problem here from my pov is introduced by the use of the Docker provided repositories (and hence the use of docker-engine-1.7.0 package) for installing the docker daemon, while this can be useful to get the bleeding edge, it often introduces more issues than it resolves. The CentOS packages in my experience has worked better than the ones put together by upstream.

With regards to technical debt, as an example, taking the following task into account, while this is fine for most cases; this overrides platform specific changes that may be required to run the daemon. The technical debt introduced by changes like these are more significant imho. This introduces https://github.com/docker/docker/issues/11135 into the deployment. 

```yaml
- name: create local docker service override
  sudo: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/local.conf
    content: |
      [Service]
      EnvironmentFile=-/etc/sysconfig/docker
      ExecStart=
      ExecStart=/usr/bin/docker -d -H fd:// $other_arg
  notify:
    - reload docker
  tags:
    - docker
```

This should really be adding the following to the end of `/etc/sysconfig/docker` instead to achieve what it seems to be doing.

```sh
OPTIONS="${OPTIONS} --dns {{ private_ipv4 }} --dns-search service.{{ consul_dns_domain }} --log-driver=syslog"
```

The case that I ran into the issue was mainly because we wanted to set-up docker storage prior to deployment of MANTL. I suppose this can be made optional at the very least; to not rely on upstream provided packaging for docker. Might submit a PR for that as that might be less controversial.

As for the cloud provider; at the moment we are using on premise IaaS ([oVirt](http://www.ovirt.org/Home)) and AWS. For the former we use a clean CentOS 7.1 minimal but install docker and [set-up storage](http://www.projectatomic.io/docs/docker-storage-recommendation/) so as to use [device-mapper over loopback](http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/).

Trying to achieve reproducible builds (well as best as possible) across all platform versions and providers is hard task. To balance this with manlt behaving functionally equivalent across the versions, I'd recommend relying on the platform provided versions of docker daemon and other packages unless there is an obvious reason (eg: some feature that exists only in upstream). With Red Hat's current indulgence in docker, the docker package on CentOS should be relatively up-to-date and stable.

**Comment by BrianHicks** [comment] 2015-09-09 13:21
Just as a bit of context, we're using the upstream package because of a bug in the interaction between the CentOS packaged docker daemon and selinux that meant we couldn't mount volumes from the glusterfs mount.

Regarding the sysconfig file, I addressed it in docker/docker#15043, see the discussion there. The long and the short of it: they want people to use overrides. See docker/docker#15301 for the updated documentation. Since we don't want to package Docker ourselves (yet) we're going to comply with upstream's recommendation on how to fix the issue we had.

We'll review your PR, thanks for submitting it.

**Comment by abn** [comment] 2015-09-09 15:52
@BrianHicks thanks for the reply; that definitely puts things into context. Note that the `-H fd://`  in the current local.conf file will cause issues with CentOS 7.1. See docker/docker#11135.

Is there an issue open with Red Hat/CentOS for the SELinux issue? Oh, and +1 for not re-packaging.

**Comment by BrianHicks** [comment] 2015-09-10 14:47
It was actually an issue with Docker, not SELinux. Basically, it didn't know how to correctly request access to a different mount, even when the flag was correct specified. Just for visibility, would you mind opening a separate ticket about the `-H fd://` issue please?

**Comment by abn** [comment] 2015-09-11 01:51
Ah; so I'd assume that using the CentOS docker-1.7.1 package should work.

Created #695 to capture the socket activation issue.

**Comment by stevendborrelli** [comment] 2015-11-10 18:40
We're going to move back to the CentOS versions of Docker unless there are any objections. 

@abn @eirslett

**Comment by stevendborrelli** [comment] 2015-11-13 22:11
Closing as #803 has been merged.

**Closed by stevendborrelli** 2015-11-13 22:11 UTC
Labels: bug

**Comment by ryane** [comment] 2015-11-16 13:26
fyi, until we get a new version of the image published, vagrant builds will fail with the `docker-engine conflict`. see #815
