### ISSUE TITLE
Error on 1st playbook run after the VMs are launched.

### ISSUE THREAD

**Issue by linuxbsdfreak** [CiscoCloud/microservices-infrastructure#537] opened 2015-06-30 13:48 UTC
```
TASK: [consul | wait for leader] ********************************************** 
failed: [mi-control-01] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:31.219655", "end": "2015-06-30 10:19:37.931316", "rc": 1, "start": "2015-06-30 10:19:06.711661", "warnings": []}
stdout: No Consul leader elected in 30 seconds
failed: [mi-control-02] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:31.228493", "end": "2015-06-30 10:19:37.940317", "rc": 1, "start": "2015-06-30 10:19:06.711824", "warnings": []}
stdout: No Consul leader elected in 30 seconds
failed: [mi-worker-001] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:31.277490", "end": "2015-06-30 10:19:37.948252", "rc": 1, "start": "2015-06-30 10:19:06.670762", "warnings": []}
stdout: No Consul leader elected in 30 seconds
failed: [mi-worker-003] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:31.241176", "end": "2015-06-30 10:19:37.957695", "rc": 1, "start": "2015-06-30 10:19:06.716519", "warnings": []}
stdout: No Consul leader elected in 30 seconds
```
Once the playbook is rerun it works. Could you check?

**Comment by ipolyzos** [comment] 2015-09-09 15:52
The same happens to me also in an openstack deployment. The issue is repeatable and happen in every subsequent run attempted. Interesting though is that SSHing into the machine and machine and run the individual command or the script manually works as expected!

**Comment by stevendborrelli** [comment] 2015-09-10 11:49
@ipolyzos it could just be a timing issue. Consul leader elections usually happen in a couple of seconds, so we need to figure out why the 30 second timeout is not working.

**Comment by ipolyzos** [comment] 2015-09-10 13:34
@stevendborrelli thanks for the help. Running behind proxy turned out to be  a typo in no_proxy configuration

**Comment by stevendborrelli** [comment] 2015-09-11 15:31
@ipolyzos can we close this issue?

**Comment by ipolyzos** [comment] 2015-09-11 19:23
@stevendborrelli yes please feel free to do so.

**Closed** 2015-09-11 19:25 UTC

**Comment by vallard** [comment] 2016-01-05 06:38
@ipolyzos where did you put the no_proxy config?  I'm running behind a proxy and can't get this working.

**Comment by ipolyzos** [comment] 2016-01-05 07:26
@vallard proxy configuration has been set on playbook environmental variables
